# Generated by Django 2.1.7 on 2019-03-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('birth_date', models.DateField()),
                ('sex', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'unspecified')])),
                ('nationality', models.CharField(max_length=140)),
                ('alive', models.BooleanField(null=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/noimg.jpg', upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='ActorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('kind', models.IntegerField(choices=[(0, 'movie'), (1, 'actor')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ManyToManyField(blank=True, related_name='actor_credits', to='core.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='AwardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('logo', models.ImageField(blank=True, default='posters/noimg.jpg', upload_to='posters')),
                ('actors', models.ManyToManyField(blank=True, related_name='acting_credits', to='core.Actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
            options={
                'ordering': ('-release_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='movie_credits', to='core.Movie'),
        ),
    ]
