# Generated by Django 2.1.7 on 2019-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('category', models.IntegerField(choices=[(0, 'Action'), (1, 'Adventure'), (2, 'Animation'), (3, 'Biography'), (4, 'Comedy')])),
            ],
        ),
    ]
