# Generated by Django 2.1.7 on 2019-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, default='logos/noimg.jpg', upload_to='logos'),
        ),
    ]
