# Generated by Django 2.1.7 on 2019-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, default='logos/noimg.jpg', null=True, upload_to='logos'),
        ),
    ]
