# Generated by Django 2.1.7 on 2019-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('category', models.IntegerField(choices=[(0, 'action'), (1, 'adventure'), (2, 'animation'), (3, 'biography'), (4, 'comedy'), (5, 'thriller')])),
                ('logo', models.ImageField(blank=True, default='posters/noimg.jpg', upload_to='posters')),
            ],
        ),
    ]
