# Generated by Django 2.1.7 on 2019-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190310_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.IntegerField(choices=[(0, 'action'), (1, 'adventure'), (2, 'animation'), (3, 'biography'), (4, 'comedy'), (5, 'thriller')]),
        ),
    ]
