# Generated by Django 2.1.7 on 2019-03-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190310_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date', 'title')},
        ),
    ]
