# Generated by Django 2.1.7 on 2019-03-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190310_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, default='posters/noimg.jpg', upload_to='posters'),
        ),
    ]
