# Generated by Django 2.1.7 on 2019-03-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190310_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('birth_date', models.DateField()),
                ('sex', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'unspecified')])),
                ('nationality', models.CharField(max_length=140)),
                ('alive', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acting_credits', to='core.Actor'),
        ),
    ]
