# Generated by Django 2.1.7 on 2019-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190311_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/noimg.jpg', upload_to='avatars'),
        ),
    ]
