# Generated by Django 2.1.7 on 2019-03-11 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Actor'),
        ),
        migrations.AlterField(
            model_name='award',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Movie'),
        ),
    ]
